name: Java CI with Maven on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest  # ✅ Changed to Windows

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
          path: C:\Users\runneradmin\.m2  # ✅ Windows path for Maven cache
          key: maven-${{ hashFiles('**\pom.xml') }}
          restore-keys: maven-

    - name: Install Dependencies
      run: mvn clean install -DskipTests

    - name: Install ChromeDriver
      uses: browser-actions/setup-chrome@latest

    - name: Run Selenium Tests
      run: mvn verify

    - name: Upload Cucumber Reports
      uses: actions/upload-artifact@v4
      if: success() || failure()  # ✅ Ensures upload even if tests fail
      with:
          name: cucumber-html-report
          path: target/  # ✅ Use forward slash `/` for compatibility

    - name: Upload Selenium Logs (if any)
      uses: actions/upload-artifact@v4
      if: success() || failure()  # ✅ Ensures upload even if tests fail
      with:
          name: selenium-logs
          path: target/selenium.log
