name: Java CI with Maven on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build:

    runs-on: windows-latest  # ✅ Changed to Windows

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install ChromeDriver
      uses: browser-actions/setup-chrome@latest

    - name: Verify ChromeDriver
      run: chrome --version && chromedriver --version

      
    - name: Build feature test
      run: mvn -B clean verify
  

    - name: Upload Cucumber Reports      
      if: success() || failure()  # ✅ Ensures upload even if tests fail
      uses: PavanMudigonda/html-reporter-github-pages@v1.2
      with:
          name: cucumber-html-report
          test_results: target/  # ✅ Use forward slash `/` for compatibility
          keep_reports: 20
          gh_pages: main
          env: CI
          

  
